from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_receipt(payment, output_path=None):
    """Generate a PDF receipt for a payment"""
    
    if not output_path:
        # Create exports directory if it doesn't exist
        os.makedirs('exports/receipts', exist_ok=True)
        output_path = f'exports/receipts/receipt_{payment.receipt_no}.pdf'
    
    # Create PDF
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # School header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1*inch, height - 1*inch, "SCHOOL BILLING SYSTEM")
    
    c.setFont("Helvetica", 12)
    c.drawString(1*inch, height - 1.3*inch, "Official Receipt")
    
    # Receipt details
    y = height - 2*inch
    c.setFont("Helvetica-Bold", 10)
    c.drawString(1*inch, y, f"Receipt Number: {payment.receipt_no}")
    
    y -= 0.3*inch
    c.setFont("Helvetica", 10)
    c.drawString(1*inch, y, f"Date: {payment.payment_date.strftime('%Y-%m-%d')}")
    
    y -= 0.3*inch
    c.drawString(1*inch, y, f"Payment Method: {payment.payment_method.upper()}")
    
    y -= 0.3*inch
    c.drawString(1*inch, y, f"Amount Paid: ")
    
    y -= 0.3*inch
    c.drawString(1*inch, y, f"Bill ID: {payment.bill_id}")
    
    if payment.notes:
        y -= 0.3*inch
        c.drawString(1*inch, y, f"Notes: {payment.notes}")
    
    # Footer
    y = 1*inch
    c.drawString(1*inch, y, "Thank you for your payment!")
    c.drawString(1*inch, y - 0.3*inch, "Generated by School Billing System MPV")
    
    c.save()
    return output_path
